### ISSUE TITLE
how to generate the corresponding CMakeList.txt in a new aosp project

### ISSUE THREAD

**Issue by liihag** [ogtc890215/aosp-cmake#1]
HI,I am coding on a aosp on a NXP paltform and needed to generate detail CMakeList Files, i notice that  can generate by this way:[ AOSP CLion project generator](https://android.googlesource.com/platform/build/soong/+/HEAD/docs/clion.md
), but cannot generate the frameworks/av/services/audiopolicy/CMakeList.txt 

so,how to generate all the CMakeList files? it seems that you have a different way with google.

**Comment by ogtc890215** [comment]
The best way is that you transform Android.mk to Android.bp.
